.TH luafetch 1 "2026-06-20" "version 1.0" "User Commands"
.SH NAME
luafetch \- Fast Lua terminal animation & 3D graphics engine
.SH SYNOPSIS
.B luafetch
.SH DESCRIPTION
.B luafetch
is a fast engine written in C and Lua for rendering 3D graphics and playing complex animations directly inside the Linux terminal.
.SH AUTHOR
Svyatoslav (Delta Tech)
.SH SEE ALSO
.BR lua (1)
